benchmarks_coverage = {
    "ACTIVE THEORY": {
        "current": ["02_ART_DIRECTION", "05_MOTION_SYSTEM", "37_CREATIVE_TECH_SYSTEM"],
        "should": ["22_CREATIVE_DIRECTION_GENERATOR", "26_ANIMATION_LIBRARY", "40_EXPERIENCE_ARCHITECTURE_SYSTEM", "21_AWWWARDS_EVALUATION_SYSTEM", "27_SCROLL_STORY_LIBRARY", "33_PORTFOLIO_SYSTEM", "34_VISUAL_LANGUAGE_LIBRARY", "44_SYSTEM_PROMPTS_LIBRARY"]
    },
    "BUTTERMAX": {
        "current": ["04_TYPOGRAPHY_SYSTEM", "10_COLOR_SYSTEM", "36_CONTENT_DESIGN_SYSTEM"],
        "should": ["17_CONVERSION_ARCHITECTURE", "20_DESIGN_DECISION_ENGINE", "28_LAYOUT_PATTERNS_LIBRARY", "29_CASE_STUDY_LIBRARY", "31_LUXURY_BRAND_SYSTEM", "35_DESIGN_TOKENS", "41_DESIGN_GOVERNANCE_SYSTEM"]
    },
    "RESN": {
        "current": ["05_MOTION_SYSTEM", "06_INTERACTION_SYSTEM", "07_STORYTELLING_SYSTEM", "37_CREATIVE_TECH_SYSTEM"],
        "should": ["21_AWWWARDS_EVALUATION_SYSTEM", "26_ANIMATION_LIBRARY", "27_SCROLL_STORY_LIBRARY", "33_PORTFOLIO_SYSTEM", "34_VISUAL_LANGUAGE_LIBRARY"]
    },
    "LOCOMOTIVE": {
        "current": ["04_TYPOGRAPHY_SYSTEM", "06_INTERACTION_SYSTEM", "08_LAYOUT_ENGINE", "11_FRONTEND_ARCHITECTURE", "40_EXPERIENCE_ARCHITECTURE_SYSTEM"],
        "should": ["26_ANIMATION_LIBRARY", "27_SCROLL_STORY_LIBRARY", "28_LAYOUT_PATTERNS_LIBRARY", "29_CASE_STUDY_LIBRARY", "33_PORTFOLIO_SYSTEM"]
    },
    "INSTRUMENT": {
        "current": ["16_INFORMATION_ARCHITECTURE", "19_ENTERPRISE_CLIENT_SYSTEM", "30_ENTERPRISE_UX_SYSTEM"],
        "should": ["17_CONVERSION_ARCHITECTURE", "20_DESIGN_DECISION_ENGINE", "29_CASE_STUDY_LIBRARY", "41_DESIGN_GOVERNANCE_SYSTEM", "44_SYSTEM_PROMPTS_LIBRARY"]
    },
    "BASIC": {
        "current": ["01_DESIGN_OS", "03_VISUAL_RULES", "07_STORYTELLING_SYSTEM", "18_PREMIUM_PERCEPTION_SYSTEM"],
        "should": ["20_DESIGN_DECISION_ENGINE", "21_AWWWARDS_EVALUATION_SYSTEM", "28_LAYOUT_PATTERNS_LIBRARY", "29_CASE_STUDY_LIBRARY", "34_VISUAL_LANGUAGE_LIBRARY", "35_DESIGN_TOKENS"]
    },
    "FANTASY": {
        "current": ["09_COMPONENT_SYSTEM", "40_EXPERIENCE_ARCHITECTURE_SYSTEM"],
        "should": ["17_CONVERSION_ARCHITECTURE", "19_ENTERPRISE_CLIENT_SYSTEM", "21_AWWWARDS_EVALUATION_SYSTEM", "23_FUTURE_PROOFING_SYSTEM", "30_ENTERPRISE_UX_SYSTEM", "32_AI_PRODUCT_SYSTEM"]
    },
    "DOGSTUDIO": {
        "current": ["37_CREATIVE_TECH_SYSTEM"],
        "should": ["22_CREATIVE_DIRECTION_GENERATOR", "26_ANIMATION_LIBRARY", "27_SCROLL_STORY_LIBRARY", "33_PORTFOLIO_SYSTEM", "34_VISUAL_LANGUAGE_LIBRARY"]
    },
    "MONKS": {
        "current": ["37_CREATIVE_TECH_SYSTEM"],
        "should": ["23_FUTURE_PROOFING_SYSTEM", "30_ENTERPRISE_UX_SYSTEM", "32_AI_PRODUCT_SYSTEM", "41_DESIGN_GOVERNANCE_SYSTEM"]
    },
    "BUREAU BORSCHE": {
        "current": ["01_DESIGN_OS", "04_TYPOGRAPHY_SYSTEM", "08_LAYOUT_ENGINE", "33_PORTFOLIO_SYSTEM"],
        "should": ["22_CREATIVE_DIRECTION_GENERATOR", "28_LAYOUT_PATTERNS_LIBRARY", "31_LUXURY_BRAND_SYSTEM", "34_VISUAL_LANGUAGE_LIBRARY", "35_DESIGN_TOKENS"]
    }
}

for name, data in benchmarks_coverage.items():
    curr = len(data["current"])
    sho = len(data["should"])
    total = curr + sho
    cov = int(round(curr / total * 100))
    print(f"### {name}")
    print("Currently Referenced:")
    for f in data["current"]:
        print(f"* {f}")
    print("\nShould Also Influence:")
    for f in data["should"]:
        print(f"* {f}")
    print(f"\nCoverage:\n{cov}%\n")
